// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: demo.proto

package server

import (
	"context"

	"demo/demo"
	"demo/internal/logic"
	"demo/internal/svc"
)

type DemoServer struct {
	svcCtx *svc.ServiceContext
	demo.UnimplementedDemoServer
}

func NewDemoServer(svcCtx *svc.ServiceContext) *DemoServer {
	return &DemoServer{
		svcCtx: svcCtx,
	}
}

func (s *DemoServer) Ping(ctx context.Context, in *demo.Request) (*demo.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *DemoServer) Callback(ctx context.Context, in *demo.CbRequest) (*demo.Response, error) {
	l := logic.NewCallbackLogic(ctx, s.svcCtx)
	return l.Callback(in)
}
