name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 手动触发事件
  workflow_dispatch:
    inputs:
      tags:
        description: 'update source image'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build grpc image
        uses: docker/build-push-action@v6.3.0
        with:
          path_context:./grpc
          file: ./grpc/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            laotie255/pingpong:grpc
      - name: Build http image
        uses: docker/build-push-action@v6.3.0
        with:
          path_context:./http
          file: ./http/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            laotie255/pingpong:http